version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    volumes:
      - ./src/.env:/app/.env
    networks:
      - web_net
  nginx:
    image: nginx:1.25.1
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web_net
  database:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=local_db
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_pass
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pg_data_local:/var/lib/postgresql/data/
    networks:
      - web_net
  redis:
    image: redis:7.0.11-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - web_net
  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=local_pass
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
    healthcheck:
      test: curl -u "elastic:local_pass" http://127.0.0.1:9200
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - web_net
  rabbitmq:
    image: rabbitmq:3.11.16-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data_local:/var/lib/rabbitmq/
        - rabbitmq_log_local:/var/log/rabbitmq
    networks:
        - web_net
  vector:
    image: timberio/vector:nightly-alpine
    environment:
      - LOG=info
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=local_pass
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/vector.toml:/etc/vector/vector.toml:ro
    networks:
      - web_net
volumes:
  pg_data_local:
  redis_data:
  elasticsearch_data:
  rabbitmq_data_local:
  rabbitmq_log_local:
networks:
  web_net:
    driver: bridge
