name: Deploy using infra repository

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy backend
        run: |
          curl  
          -XPOST  
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer {{ secrets.INFRA_TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/Kelvedler/flask_app-infra/dispatches 
          -d '{"event_type":"deploy-backend"}
